### ISSUE TITLE
Not working well with cytoscape.js 2.5.4

### ISSUE THREAD

**Issue by metincansiper** [jhonatandarosa/cytoscape.js-noderesize#3]
Hi,
I realized that the extension is not working well with cytoscape.js 2.5.4. It draws the node-resize handles in wrong places and increases the height of the canvas much. I solved that problem by changing the sizeCanvas function as below.

```
  function sizeCanvas() {
        $canvas
                .attr('height', $container.height())
                .attr('width', $container.width())
                .css({
                  'position': 'relative',
                  'top': -( $canvas.offset().top - $container.offset().top ),
                  'left': -( $canvas.offset().left - $container.offset().left ),
                  'z-index': '999'
                });
      }
```

**Comment by metincansiper** [comment]
I realized that my previous solution did not solved the canvas size problem. I solved this problem by making use of the following commit in cytoscape.js-edgehandles "https://github.com/cytoscape/cytoscape.js-edgehandles/commit/4dafdaa48cdbc09ff6cd1ca2f7398c84424137f0". As it is done in that commit, I have overwrite the sizeCanvas function in the following way.

```
     var _sizeCanvas = debounce( function(){
        $canvas
          .attr( 'height', $container.height() )
          .attr( 'width', $container.width() )
          .css( {
            'position': 'absolute',
            'top': 0,
            'left': 0,
            'z-index': '999'
          } )
        ;

        setTimeout(function(){
          var canvasBb = $canvas.offset();
          var containerBb = $container.offset();

          $canvas
            .css( {
              'top': -( canvasBb.top - containerBb.top ),
              'left': -( canvasBb.left - containerBb.left )
            } )
          ;
        }, 0);
      }, 250 );

      function sizeCanvas() {
        _sizeCanvas();
      }
```

And I just changed the 'z-index' in that commit as '999' and, copy-pasted the 'debounce' in that commit.

Canvas size problem seems to be solved now.

**Comment by jhonatandarosa** [comment]
Hi, 
thanks to identify the problem.
Didn't have much time to test with later versions yet, we're still using 2.4.0 in our application =/
Just committed the change. Seems to be working with 2.5.4+ now.
